### ISSUE TITLE
ocrd-cis-ocropy-recognize -J fails with error

### ISSUE THREAD

**Issue by stweil** [cisocrgroup/ocrd_cis#36]
Running `ocrd-cis-ocropy-recognize -J` throws an exception:

    [...]
    AttributeError: 'OcropyRecognize' object has no attribute 'parameter'

**Comment by stweil** [comment]
@kba, this might also be a bug in OCR-D/core.

**Comment by kba** [comment]
> @kba, this might also be a bug in OCR-D/core.

Not really, as long as `__init__` doesn't assume that `process` is to be called (which it isn't e.g. when dumping the ocrd-tool.json), it should work.

This is the only processor that has any setup in __init__ and it's easy to fix by moving the model init code to process. All other `ocrd-cis` dump JSON just fine.

Maybe it would make sense to rename `ocrd-cis-ocropy-rec` since that has no ocrd interface.
